kind: ConfigMap
apiVersion: v1
metadata:
  name: patron-comp-phase2-java-atk-svc-apm-configmap
data:
  _JAVA_OPTIONS: -javaagent:/javaagent/opentelemetry-javaagent.jar -Dotel.javaagent.extensions=/javaagent/extensions
  OTEL_SERVICE_NAME: patron-comp-phase2-java-atk
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_LOGS_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: 'https://qa-apm-server.elastic.svc.cluster.local:8200'



kubectl get namespace "stucked-namespace" -o json \
  | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" \
  | kubectl replace --raw /api/v1/namespaces/stucked-namespace/finalize -f -



Map dynamic_templates = new HashMap();
for (entry in ctx._metric_descriptions.entrySet()) {
  String name = entry.getKey();
  Map description = entry.getValue();
  String metric_type = description.type;
  if (metric_type == "histogram") {
    dynamic_templates[name] = "histogram";
  } else if (metric_type == "summary") {
    dynamic_templates[name] = "summary";
  } else {
    dynamic_templates[name] = "double";
  }
}
ctx._dynamic_templates = dynamic_templates;
ctx.remove("_metric_descriptions");
