apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prd-sands-resort-royale

namePrefix: prd-

labels:
  - includeSelectors: true
    pairs:
      env: prd

resources:
  - credentials.yaml
  - ../../base
  - pod-auto-scaler.yaml


patches:
  - path: deployment.yaml
  - path: configmap.yaml
  - path: env.yaml
  - path: credentials.yaml
  - path: anti-affinity.yaml
  - path: replicas.yaml


overlays/prd/kustomization.yaml
  14:3      error    no new line character at the end of file  (new-line-at-end-of-file)
  14:1      error    trailing spaces  (trailing-spaces)

make: *** [Makefile:19: yaml_lint] Error 1
Failed to create Argo CD app for prd/sands-resort-royale.
