apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prd-sands-resort-royale

namePrefix: prd-

labels:
  - includeSelectors: true
    pairs:
      env: prd

resources:
  - credentials.yaml
  - ../../base
  - pod-auto-scaler.yaml


patches:
  - path: deployment.yaml
  - path: configmap.yaml
  - path: env.yaml
  - path: credentials.yaml
  - path: anti-affinity.yaml
  - path: replicas.yaml
